### ISSUE TITLE
What is the build process?

### ISSUE THREAD

**Issue by Taiiwo** [ZeCryptic/osu-cat#28]
I'm forking this project and making it work for LoL. What do you use to build the project? I've tried cx_freeze, PyInstaller, and py2exe and they all give me the same error in the compile version (even though it works when I run the uncompiled version):

```
Exception in thread Thread-343:
Traceback (most recent call last):
  File "C:\Users\taiiwo\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\taiiwo\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\taiiwo\AppData\Local\Programs\Python\Python35\lib\site-packages\keyboard\__init__.py", line 292, in listen
  File "C:\Users\taiiwo\AppData\Local\Programs\Python\Python35\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
  File "C:\Users\taiiwo\AppData\Local\Programs\Python\Python35\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
```

I realize this is a bug with `keyboard` and not with this project, I was just looking for some build advice.

**Comment by ZeCryptic** [comment]
You actually have to change a line in the keyboard module: https://github.com/boppreh/keyboard/issues/157#issuecomment-389910903

I used Pyinstaller to build the project. Hope this helps
